"""Convert a markdown investment memo to a styled PDF and save it to the reports/ directory."""

import os
import re

import markdown
import weasyprint

_CSS = """
@page {
    margin: 1.8cm 2cm;
    @bottom-center {
        content: "Page " counter(page) " of " counter(pages);
        font-size: 9pt;
        color: #888;
    }
}
body {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 10.5pt;
    line-height: 1.6;
    color: #1f2328;
}
h1 { font-size: 17pt; color: #1a1a2e; border-bottom: 2px solid #3b82d4; padding-bottom: 4px; margin-top: 0; }
h2 { font-size: 12.5pt; color: #1a1a2e; border-bottom: 1px solid #e5e7eb; padding-bottom: 2px; margin-top: 20px; }
h3 { font-size: 10.5pt; color: #374151; margin-top: 12px; }
p  { margin: 5px 0; }
ul, ol { padding-left: 1.4em; margin: 5px 0; }
li { margin-bottom: 3px; }

/* ── Tables — overflow-safe ── */
table {
    border-collapse: collapse;
    width: 100%;
    table-layout: fixed;        /* prevents columns expanding beyond page */
    font-size: 9pt;
    margin: 10px 0;
    word-break: break-word;     /* long cell values wrap instead of overflow */
}
th {
    background: #f0f4ff;
    color: #1a1a2e;
    border: 1px solid #d1d5db;
    padding: 4px 6px;
    text-align: left;
    white-space: normal;
    overflow-wrap: break-word;
}
td {
    border: 1px solid #e5e7eb;
    padding: 3px 6px;
    white-space: normal;
    overflow-wrap: break-word;
    max-width: 180px;           /* cap any single column width */
}
tr:nth-child(even) td { background: #f9fafb; }

/* Wide tables: allow horizontal scroll in browser preview, clip in PDF */
.table-wrap { overflow-x: auto; }

code { background: #f3f4f6; padding: 1px 4px; border-radius: 3px; font-size: 9pt; }
pre  { background: #f3f4f6; padding: 10px; border-radius: 4px; font-size: 9pt;
       white-space: pre-wrap; word-break: break-all; }
blockquote { border-left: 3px solid #3b82d4; margin: 6px 0; padding: 4px 10px; color: #57606a; }
hr { border: none; border-top: 1px solid #e5e7eb; margin: 14px 0; }
.disclaimer { font-size: 9pt; color: #6b7280; border-top: 1px solid #e5e7eb; margin-top: 20px; padding-top: 6px; }
.footer { font-size: 9pt; color: #9ca3af; text-align: center; margin-top: 28px;
          border-top: 1px solid #e5e7eb; padding-top: 6px; }
"""


def _md_to_html(memo: str, ticker: str) -> str:
    body = markdown.markdown(
        memo,
        extensions=["tables", "fenced_code", "nl2br"],
    )
    # Wrap trailing disclaimer paragraph in a styled div
    body = re.sub(
        r"(<p>(?:This report is for informational purposes|Disclaimer).*?</p>)",
        r'<div class="disclaimer">\1</div>',
        body,
        flags=re.IGNORECASE | re.DOTALL,
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<style>{_CSS}</style>
</head>
<body>
{body}
<div class="footer">Generated by StocksAgent &mdash; {ticker}</div>
</body>
</html>"""


def save_pdf(memo: str, ticker: str, output_path: str) -> str:
    """
    Render *memo* (markdown) as a PDF and write it to *output_path*.

    Creates the parent directory if it does not exist.
    Overwrites any existing file at the same path.

    Returns the absolute path to the written PDF.
    """
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    html = _md_to_html(memo, ticker)
    weasyprint.HTML(string=html).write_pdf(output_path)
    return os.path.abspath(output_path)
